version: "3.7"
services:
    hello-service:
        image: hello-api
        deploy:
            replicas: 4
            resources:
                limits:
                    cpus: "0.2"
                    memory: 50M
            restart_policy:
                condition: on-failure
        ports:
            - "4000:80"
        depends_on:
            - "redis-service"
        networks:
            - webnet
    redis-service:
        image: redis
        ports:
            - "6379:6379"
        networks:
            - webnet
networks:
    webnet: