version: "3"
services:
    hello-service:
        image: hello-api
        deploy:
            replicas: 4
            resources:
                limits:
                    cpus: "0.2"
                    memory: 50M
            restart_policy:
                condition: on-failure
        ports:
            - "4000:80"
        networks:
            - webnet
networks:
    webnet: